
rmdisk -path=/hola/gerson/ver/disk1.dk

mKdisk -size=3 -fit= BF -unit=m -path= /hola/gerson/ver/disk1.dk


fdisk -path=/hola/gerson/ver/disk1.dk -size=90 -name=myPartition 
fdisk -path=/hola/gerson/ver/disk1.dk -size=90 -name=myPartition1
pause
fdisk -type=p -path=/hola/gerson/ver/disk1.dk -size=90 -name=myPartition2
fdisk -type=e -path=/hola/gerson/ver/disk1.dk -size=90 -name=myPartition3
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic1
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic2
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic3
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic4 
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic5 -fit=wb
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic6 
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic7
fdisk -type=l -path=/hola/gerson/ver/disk1.dk -size=10 -name=logic8

mount -path=/hola/gerson/ver/disk1.dk -name=myPartition1

mkfs -id=571A -type=fast

#mkfile -size=15 -path=/gerson/aja/yea.txt -r

#CREACION DE CARPETAS

login -usuario=root -password=123 -id=571A
Mkdir -P -path=/maincra/momiradios
Mkdir -P -path=/yea
Mkdir -P -path=/home
Mkdir -P  -path=/home/archivos/mia/fase2
Mkdir -P  -path=/home/archivos/mia/carpeta2
Mkdir -P  -path=/home/archivos/mia/z
Mkdir -P  -path=/home/archivos/mia/carpeta3/carpeta7/carpeta8/carpeta9/carpeta10/carpeta11
Mkdir -P  -path=/home/archivos/mia/carpeta4/carpeta7/carpeta8/carpeta9/carpeta10/carpeta11/carpeta7/carpeta8/carpeta9/carpeta10/carpeta11
Mkdir  -path=/home/archivos/mia/carpeta2/a1
Mkdir  -path=/home/archivos/mia/carpeta2/a2
Mkdir  -path=/home/archivos/mia/carpeta2/a3
Mkdir  -path=/home/archivos/mia/carpeta2/a4
Mkdir  -path=/home/archivos/mia/carpeta2/a5
Mkdir  -path=/home/archivos/mia/carpeta2/a6
Mkdir  -path=/home/archivos/mia/carpeta2/a7
Mkdir  -path=/home/archivos/mia/carpeta2/a8
Mkdir  -path=/home/archivos/mia/carpeta2/a9
Mkdir  -path=/home/archivos/mia/carpeta2/a10
Mkdir  -path=/home/archivos/mia/carpeta2/a10
Mkdir  -path=/home/archivos/mia/fase2/a1
#Mkdir  -path=/home/archivos/mia/fase2/a2
#Mkdir  -path=/home/archivos/mia/fase2/a3
#Mkdir  -path=/home/archivos/mia/fase2/a4
#Mkdir  -path=/home/archivos/mia/fase2/a5
#Mkdir  -path=/home/archivos/mia/fase2/a6
#Mkdir  -path=/home/archivos/mia/fase2/a7
#Mkdir  -path=/home/archivos/mia/fase2/a8
#Mkdir  -path=/home/archivos/mia/fase2/a9
#Mkdir  -path=/home/archivos/mia/fase2/a10
#Mkdir  -path=/home/archivos/mia/fase2/a11
#Mkdir  -path=/home/archivos/mia/fase2/a12
#Mkdir  -path=/home/archivos/mia/fase2/a13
#Mkdir  -path=/home/archivos/mia/fase2/a14
#Mkdir  -path=/home/archivos/mia/fase2/a15
#Mkdir  -path=/home/archivos/mia/fase2/a16
#Mkdir  -path=/home/archivos/mia/fase2/a17
#Mkdir  -path=/home/archivos/mia/fase2/a18
#Mkdir  -path=/home/archivos/mia/fase2/a19
#Mkdir  -path=/home/archivos/mia/fase2/a20
#Mkdir  -path=/home/archivos/mia/fase2/a21
#Mkdir  -path=/home/archivos/mia/fase2/a22
#Mkdir  -path=/home/archivos/mia/fase2/a23
#Mkdir  -path=/home/archivos/mia/fase2/a24
#Mkdir  -path=/home/archivos/mia/fase2/a25
#Mkdir  -path=/home/archivos/mia/fase2/a26
#Mkdir  -path=/home/archivos/mia/fase2/a27
#Mkdir  -path=/home/archivos/mia/fase2/a28
#Mkdir  -path=/home/archivos/mia/fase2/a29
#Mkdir  -path=/home/archivos/mia/fase2/a30
#Mkdir  -path=/home/archivos/mia/fase2/a31
#Mkdir  -path=/home/archivos/mia/fase2/a32
#Mkdir  -path=/home/archivos/mia/fase2/a33
#Mkdir  -path=/home/archivos/mia/fase2/a34
#Mkdir  -path=/home/archivos/mia/fase2/a35
#Mkdir  -path=/home/archivos/mia/fase2/a36
#Mkdir  -path=/home/archivos/mia/fase2/a37
#Mkdir  -path=/home/archivos/mia/fase2/a38
#Mkdir  -path=/home/archivos/mia/fase2/a39
#Mkdir  -path=/home/archivos/mia/fase2/a40
#Mkdir  -path=/home/archivos/mia/fase2/a41
#Mkdir  -path=/home/archivos/mia/fase2/a42
#Mkdir  -path=/home/archivos/mia/fase2/a43
#Mkdir  -path=/home/archivos/mia/fase2/a44
#Mkdir  -path=/home/archivos/mia/fase2/a45
#Mkdir  -path=/home/archivos/mia/fase2/a46

#Archivo 
#mkfile -path="/home/b1.txt" -size=75

mkfile -path=/home/archivos/mia/fase2/a46/hello.txt -size=80 -r -cont=/home/archivos/mia/fase2/a46/hello.txt



#CREACION DE GRUPOS
mkgrp -naMe=Archivos
mkgrp -NamE=Arqui
mkgrp -name=Orga
mkgrp -name=Compi2
#ELIMINACION DE GRUPOS
rmgrp -name=Arqui
#CREACION DE USUARIOS
Mkuser -usuario=user1 -grp=root -pwd=user1
Mkuser -usuario=user2 -grp=Compi2 -pwd=user2
Mkuser -usuario=user3 -grp=Compi2 -pwd=user3
Mkuser -usuario=user4 -grp=Compi2 -pwd=user4
Rmusr -usuario=user3


rep -id=571A -name=disk -path=/hola/myReports/hello.svg
rep -id=571A -name=tree -path=/hola/myReports/hello.svg
rep -id=571A -name=file -path=/hola/myReports/archive_content.svg -ruta=/home/archivos/mia/fase2/a46/hello.txt

logout
